import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Poppins } from 'next/font/google'

const poppins = Poppins({
  weight: ['400', '700'],
  subsets: ['latin'],
})
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'next13 tutorial project',
  description: 'Generated by create next app in Next13',
  keywords:
    'web development, webdesign, javascript, typescript, next13, react, html, css',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <main className="container">{children}</main>
      </body>
    </html>
  )
}
