import './globals.css'
import { Poppins } from 'next/font/google'
import { Suspense } from 'react'

import Header from './components/Header'
import LoadingPage from './loading'

import type { Metadata } from 'next'

const poppins = Poppins({
  weight: ['400', '700'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'next13 tutorial project',
  description: 'Generated by create next app in Next13',
  keywords:
    'web development, webdesign, javascript, typescript, next13, react, html, css',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Header />
        <Suspense fallback={<LoadingPage></LoadingPage>}>
          <main className="container">{children}</main>
        </Suspense>
      </body>
    </html>
  )
}
